#!/bin/bash

# Compares two metadata files looking for differences in the included entities
# An XSLT transformation (mdreport.xslt) is used to make an fingerprint of the two metadata
# These finger prints are then compared textually with the diff

# Note that the number of XML elements and XML attributes in an entity is part of the fingerprint that is used in the
# diff. This is a quick and dirty way to compare metadata files that were generated by a similar toolchain.

XSLTPROC=`which xsltproc`
DIFF=`which diff`

if [ $# -lt 2 ]; then
    name=`basename ${0}`
    echo "Expected two arguments"
    echo "Usage: ${name} <metadata file 1> <metadata file 2>"
    exit 1
fi

# Create two temp files
tmp1=`mktemp`
tmp2=`mktemp`

# Process them
$XSLTPROC `dirname $0`/mdreport.xslt --nonet $1 > ${tmp1}
$XSLTPROC `dirname $0`/mdreport.xslt --nonet $2 > ${tmp2}

# Diff the output
$DIFF ${tmp1} ${tmp2}

rm ${tmp1}
rm ${tmp2}