# Directory for keeping files on the remote host for use
# by the playbook
managed_file_dir: /opt/ansible/managed_files

# Timezone
# Format: IANA tz zone name (e.g. "Europe/Amsterdam")
timezone: Europe/Paris