- name: Configuration for all nodes
  hosts: all
  sudo: True
  tags: common

  roles:
  - common


- name: pyFF
  hosts: metadata
  sudo: True
  tags: pyff
  gather_facts: no

  roles:
  - pyff


- name: XMLSecTool
  hosts: metadata
  sudo: True
  tags: xmlsectool
  gather_facts: no

  roles:
  - xmlsectool


- name: Misc tools
  hosts: metadata
  sudo: True
  tags: tools
  gather_facts: no

  tasks:
  - name: Install xmllint, scons
    apt: name=libxml2-utils,scons


- name: Federation registry
  hosts: registry
  sudo: true
  tags: registry
  gather_facts: no

  roles:
  - registry


- name: Federation publish
  hosts: publish
  sudo: true
  tags: publish
  gather_facts: no

  roles:
  - publish

# - name: Metadata publication
#  hosts: publish
#  sudo: true
#  tags: publish
#  gather_facts: no
