---

# Load the apache role
dependencies:
  - role: apache
    vhosts:
      # Note: config path needs a relative path because it will be loaded from the apache role
    - config: "{{ lookup('template', role_path+'/../publish/publish.conf.j2') }}"
      name: "{{ publish_vhost_name }}"
      ip: "*" #"{{ publish_vhost_ipv4 }}"
      port: 443
      ssl_certificate: "{{ publish_ssl_certificate }}"
      ssl_key: "{{ publish_ssl_key }}"
      ssl: yes

    - config: "{{ lookup('file', role_path+'/../publish/publish.conf.j2') }}"
      name: "{{ publish_vhost_name }}"
      ip: "*" # "{{ publish_vhost_ipv4 }}"
      port: 80
      ssl: no

